version: '3.8'

services:
  bot:
    build: .
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: assyria_bot_db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
